version: '3'
services:
  api:
    build: .
    restart: always
    ports:
      - '9999:9999'
    volumes:
      - ./src:/app/src
      - ./~dev:/app/~dev
    command: yarn start
    env_file:
      - .env
